# Generated by Django 5.2.8 on 2025-11-18 04:24

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30, unique=True)),
                ('category_name_ky', models.CharField(max_length=30, null=True, unique=True)),
                ('category_name_en', models.CharField(max_length=30, null=True, unique=True)),
                ('category_name_ru', models.CharField(max_length=30, null=True, unique=True)),
                ('category_name_de', models.CharField(max_length=30, null=True, unique=True)),
                ('category_image', models.ImageField(upload_to='cate_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_name_ky', models.CharField(max_length=100, null=True)),
                ('product_name_en', models.CharField(max_length=100, null=True)),
                ('product_name_ru', models.CharField(max_length=100, null=True)),
                ('product_name_de', models.CharField(max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('owner', models.CharField(max_length=60)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('product_image', models.ImageField(upload_to='product_photo')),
                ('description', models.TextField()),
                ('description_ky', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('description_de', models.TextField(null=True)),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
