# Generated by Django 5.2.8 on 2025-11-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ajybek_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
